create TABLE IF NOT EXISTS films(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  description varchar(200),
  release_date date,
  duration int NOT NULL,
  rating_id int NOT NULL
  CONSTRAINT positive_duration CHECK (duration > 0),
  CONSTRAINT fields_uniqueness UNIQUE (name, description, release_date, duration)
);

create TABLE IF NOT EXISTS genres (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar UNIQUE NOT NULL
);

create TABLE IF NOT EXISTS ratings (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar UNIQUE NOT NULL,
  description varchar(200)
);

create TABLE IF NOT EXISTS film_genre (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id int NOT NULL,
  genre_id int NOT NULL
);

create TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar UNIQUE NOT NULL,
  login varchar NOT NULL,
  name varchar NOT NULL,
  birthday date
  CONSTRAINT birthday_in_past CHECK (birthday < now())
);

create TABLE IF NOT EXISTS friends (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  friend_1_id int NOT NULL,
  friend_2_id int NOT NULL,
  status_id int NOT NULL
);

create TABLE IF NOT EXISTS statuses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar UNIQUE NOT NULL
);

create TABLE IF NOT EXISTS likes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id int NOT NULL,
  user_id int NOT NULL
);

CREATE TABLE IF NOT EXISTS director
(
    director_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_name text NOT NULL
);

CREATE TABLE IF NOT EXISTS film_director
(
    director_id int,
    film_id     int,
    PRIMARY KEY (director_id, film_id)
);

alter table films add CONSTRAINT IF NOT EXISTS fk_film_rating
    FOREIGN KEY(rating_id)
	REFERENCES ratings(id)
	on update cascade ON DELETE RESTRICT ;
	
alter table film_genre add CONSTRAINT IF NOT EXISTS fk_film_id
    FOREIGN KEY(film_id)
	REFERENCES films(id)
	on update cascade ON DELETE CASCADE;
	
alter table film_genre add CONSTRAINT IF NOT EXISTS fk_genre_id
    FOREIGN KEY(genre_id)
	REFERENCES genres(id)
	on update cascade ON DELETE CASCADE;
	
alter table friends add CONSTRAINT IF NOT EXISTS fk_friend_1_user
    FOREIGN KEY(friend_1_id)
	REFERENCES users(id)
	on update cascade ON DELETE CASCADE;
	
alter table friends add CONSTRAINT IF NOT EXISTS fk_friend_2_user
    FOREIGN KEY(friend_2_id)
	REFERENCES users(id)
	on update cascade ON DELETE CASCADE;
	
alter table friends add CONSTRAINT IF NOT EXISTS fk_friendship_status
    FOREIGN KEY(status_id)
	REFERENCES statuses(id)
	on update cascade ON DELETE RESTRICT;
	
alter table likes add CONSTRAINT IF NOT EXISTS fk_liked_film
    FOREIGN KEY(film_id)
	REFERENCES films(id)
	on update cascade ON DELETE CASCADE;
	
alter table likes add CONSTRAINT IF NOT EXISTS fk_user_id
    FOREIGN KEY(user_id)
	REFERENCES users(id)
	on update cascade ON DELETE CASCADE;

ALTER TABLE film_director
    ADD FOREIGN KEY (film_id) REFERENCES films (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE film_director
    ADD FOREIGN KEY (director_id) REFERENCES director (director_id) ON DELETE CASCADE;